name: EVENT
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 1000000

      - name: Show Last md5
        if: ${{ github.event_name }}=='push'
        run:  |
          echo ${{ github.event_name }}=='push'