name: EVENT
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 1000000

      - name: Create test files
        if: ${{ github.event_name }}=='push'
        run:  |
          echo "openwrt-x86-64-generic-rootfs.tar.gz" > openwrt-x86-64-generic-rootfs.tar.gz
          echo "openwrt-x86-64-generic-ext4-combined.img" >openwrt-x86-64-generic-ext4-combined.img
          
      - uses: actions/upload-artifact@v2
        with:
            name: my-artifact
            path: |
               openwrt-x86-64*

