#
# This is free software, lisence use MIT.
# 

name: TP

on:
  push:
    branches: 
      - main
    paths-ignore:
      - "md5"
env:
  GITHUB_EMAIL: muyeyifeng@gmail.com	#email
  GITHUB_USER: muyeyifeng

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 1000000

      - name: Show Last md5
        run:  |
          cat md5 | tail -n 1 |awk '{print $1}'
          echo `::stop-commands::pause-logging`

      - name: Clone source code
        run:  |
          git clone  https://github.com/coolsnowwolf/lede
          git clone  https://github.com/muyeyifeng/Actions-Build-Lede-Public

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo  $DOCKER_REGISTRY_URL"lede-"${{ matrix.db-backend }}:latest
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get upgrade -y
          #=========================
          echo "$(cat lede/README.md |grep 'sudo apt-get' | sed -n 2p)"
          $(cat lede/README.md |grep "sudo apt-get" | sed -n 2p)
          sudo -E apt-get -y install tree
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: Update feeds
        run: |
          mv ./Actions-Build-Lede-Public/feeds.conf.default ./lede/feeds.conf.default
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: release
        run:  |
          cd lede
          git log -1 --format=%cd
          echo -n "$(git log -1 --format=%cd)" |md5sum >> ../md5
          cd ../ && rm -rf lede Actions-Build-Lede-Public

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./
          tag: test
          file_glob: true

      - name: Push this source
        run: |
          rm -rf lede.tar
          echo "${{ secrets.GHB_KEY }}" >github.pem
          eval `ssh-agent`
          chmod 600 github.pem
          ssh-add github.pem
          mkdir -p ~/.ssh/
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          ls
          echo "============ git config ============"
          git config --global user.email ${GITHUB_EMAIL}
          git config --global user.name ${GITHUB_USER}
          echo "============ git commit ============"
          rm -rf github.pem
          if( ${{ github.event_name == 'push' }} );then
            git add -f .
            git commit --no-verify -m "Add md5" 
          else
            git add .
            git commit -m "Add md5" 
          fi
          echo "============ git push ============"
          git push