#
# This is free software, lisence use MIT.
# 

name: TP

on:
  push:
    branches: 
      - main
    paths-ignore:
      - "md5"
env:
  GITHUB_EMAIL: muyeyifeng@gmail.com	#email
  GITHUB_USER: muyeyifeng

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 1000000

      - name: Space cleanup
        run:  |
          sudo -E apt-get install git

      - name: Clone source code
        run:  |
          git clone  https://github.com/coolsnowwolf/lede

      - name: release
        run:  |
          cd lede
          git log -1 --format=%cd
          echo -n "$(git log -1 --format=%cd)" |md5sum >> ../md5
          cd ../ && rm -rf lede

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./
          tag: test
          file_glob: true

      - name: Push this source
        run: |
          rm -rf lede.tar
          echo "${{ secrets.GHB_KEY }}" >github.pem
          eval `ssh-agent`
          chmod 600 github.pem
          ssh-add github.pem
          mkdir -p ~/.ssh/
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          ls
          echo "============ git config ============"
          git config --global user.email ${GITHUB_EMAIL}
          git config --global user.name ${GITHUB_USER}
          echo "============ git commit ============"
          rm -rf github.pem
          if( ${{ github.event_name == 'push' }} );then
            git add -f .
            git commit --no-verify -m "Add  md5" 
          else
            git add .
            git commit -m "Add  md5" 
          fi
          echo "============ git push ============"
          git push